version: '2'
services:
  account:
    image: training/webapp
    volumes:
      - ./webapp:/opt/webapp/
    restart: always
    environment:
      APP_ID: account
  premium:
    image: training/webapp
    volumes:
      - ./webapp:/opt/webapp/
    restart: always
    environment:
      APP_ID: premium
  whitelabel:
    image: training/webapp
    volumes:
      - ./webapp:/opt/webapp/
    restart: always
    environment:
      APP_ID: whitelabel
